// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Url struct {
	ID          int64
	Code        string
	OriginalUrl string
	Title       sql.NullString
	Clicks      sql.NullInt64
	CreatedAt   time.Time
	ExpiresAt   sql.NullTime
}
