// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Url struct {
	ID          int64
	Code        sql.NullString
	ShortUrl    sql.NullString
	OriginalUrl string
	Title       string
	Clicks      int64
	CreatedAt   time.Time
	ExpiresAt   time.Time
}
