// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error)
	DeleteUrl(ctx context.Context, id int64) error
	GetUrl(ctx context.Context, id int64) (Url, error)
	GetUrlByCode(ctx context.Context, code sql.NullString) (Url, error)
	GetUrlByOriginalUrl(ctx context.Context, originalUrl string) (Url, error)
	ListUrl(ctx context.Context, arg ListUrlParams) ([]Url, error)
	UpdateCodeUrl(ctx context.Context, arg UpdateCodeUrlParams) (Url, error)
	UpdateExpireUrl(ctx context.Context, arg UpdateExpireUrlParams) (Url, error)
	UpdateUrl(ctx context.Context, arg UpdateUrlParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
