// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (
    original_url,
    title,
    expires_at
) VALUES (
  $1, $2, $3
) RETURNING id, code, short_url, original_url, title, clicks, created_at, expires_at
`

type CreateUrlParams struct {
	OriginalUrl string
	Title       string
	ExpiresAt   time.Time
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl, arg.OriginalUrl, arg.Title, arg.ExpiresAt)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Clicks,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteUrl = `-- name: DeleteUrl :exec
DELETE FROM urls
WHERE id = $1
`

func (q *Queries) DeleteUrl(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUrl, id)
	return err
}

const getUrl = `-- name: GetUrl :one
SELECT id, code, short_url, original_url, title, clicks, created_at, expires_at FROM urls
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUrl(ctx context.Context, id int64) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrl, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Clicks,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listUrl = `-- name: ListUrl :many
SELECT id, code, short_url, original_url, title, clicks, created_at, expires_at FROM urls
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUrlParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUrl(ctx context.Context, arg ListUrlParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listUrl, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.Title,
			&i.Clicks,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCodeUrl = `-- name: UpdateCodeUrl :one
UPDATE urls
SET code = $2,
    short_url = $3
WHERE id = $1
RETURNING id, code, short_url, original_url, title, clicks, created_at, expires_at
`

type UpdateCodeUrlParams struct {
	ID       int64
	Code     sql.NullString
	ShortUrl sql.NullString
}

func (q *Queries) UpdateCodeUrl(ctx context.Context, arg UpdateCodeUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateCodeUrl, arg.ID, arg.Code, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Clicks,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateUrl = `-- name: UpdateUrl :one
UPDATE urls
SET code = $2,
    original_url = $3,
    title = $4
WHERE id = $1
RETURNING id, code, short_url, original_url, title, clicks, created_at, expires_at
`

type UpdateUrlParams struct {
	ID          int64
	Code        sql.NullString
	OriginalUrl string
	Title       string
}

func (q *Queries) UpdateUrl(ctx context.Context, arg UpdateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateUrl,
		arg.ID,
		arg.Code,
		arg.OriginalUrl,
		arg.Title,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.Title,
		&i.Clicks,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
